config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#top'
  get 'home/about'

  resources :users
  resources :books do
    resource    :favorites,     only: [:create, :destroy]
    resources   :book_comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many   :favorites,      dependent: :destroy
  has_many   :book_comments

  validates :title, presence: true
  validates :body,  presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many  :books,         dependent: :destroy
  has_many  :favorites,     dependent: :destroy
  has_many  :book_comments
  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2, maximum: 20},uniqueness: true
  validates :introduction,length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
      flash[:notice]="Comment was successfully created"
      redirect_to book_path(@book)
    else
      @user = @book.user
      @newbook = Book.new
      render "books/show"
    end
  end

  def destroy
    flash[:notice]="Comment was successfully destroyed."
    @book_comment = BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to request.referer
  end

  private
    def book_comment_params
      params.require(:book_comment).permit(:comment)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      render 'edit'
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    redirect_to request.referer
  end
  
  def destroy
    @book = Book.find(params[:book_id])
  	favorite = current_user.favorites.find_by(book_id: @book.id)
  	favorite.destroy
  	redirect_to request.referer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render 'edit'
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name,:introduction, :profile_image)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<h2 class="mt-3">New book</h2>
  <%= form_with model: book, local: true do |f| %>
    <p>Title</p>
    <%= f.text_field :title, class: "mb-2" %>
    <p>Opinion</p>
    <%= f.text_area :body %>
    <%= f.submit "Create Book", class: "btn btn-success mt-2" %>
  <% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@book.errors.count, "error") %></h4>
    <p><% pluralize(@book.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-5 mx-auto">
      <h1>Editing Book</h1>
      
      <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <p>Title</p>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <p>Opinion</p>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        
        <%= f.submit "Update Book", class: "btn btn-success mb-3" %>
      <% end %>
      
      <%= link_to 'Show', book_path(@book)%>
      |
      <%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@book.errors.count, "error") %></h4>
    <p><% pluralize(@book.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<div class="container">
  <div class="row mt-3">
    <div class="col-md-3">

      <%= render 'users/user', user: @user %>
      <%= render 'book', book: @book %>

    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
        </tr>

        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td class="p-3">
              <%= render 'favorites/favorite', book: book %>
            </td>
            <td class="p-3">
              コメント数：<%= book.book_comments.count %>
            </td>

          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <%= render 'books/book', book: @newbook %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>

      <table>
        <tr>
          <td class="p-3">
            <%= link_to @user do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
              <br>
              <%= @user.name %>
            <% end %>
          </td>
          <td class="p-3"><%= link_to @book.title %></td>
          <td class="p-3"><%= @book.body %></td>
          <td class="p-3">
            <%= render "favorites/favorite", book: @book %>
          </td>

          <% if @book.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-success mr-3" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %></td>
          <% end %>

        </tr>
      </table>

      <table>
        <% @book.book_comments.each do |book_comment| %>
          <tr>
            <td>
              <%= link_to user_path(book_comment.user) do %>
                <%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %>
                <br>
                <%= book_comment.user.name %>
              <% end %>
            </td>
            <td><%= book_comment.comment %></td>
            <% if book_comment.user_id == current_user.id %>
              <td>
                <%= link_to "destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </table>

      <div class="form-group">
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, class: "form-control" %>
          <%= f.submit '送信', class: "btn btn-primary mt-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete do %>
      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
        <%= book.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post do %>
      <i class="far fa-heart"></i>
      <%= book.favorites.count %>
    <% end %>
  <% end %>

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto mt-3 mb-3">Welcome to <strong><i class="fas fa-book"></i>Bookers!</strong></h1>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1 class="mt-3">welcome to <strong><i class="fas fa-book"></i>Bookers!!</strong></h1>

      <p>In <strong><i class="fas fa-book"></i>Bookers,</strong></p>
      <p>you can share and exchange your opinions , inpressions , and emotions about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in"%>
        </div>
        <div class="row">
          <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

          <h2><%= link_to 'Bookers', root_path, class:"text-light" %></h1>


          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>


          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to "Home", user_path(current_user), class: "fas fa-home nav-link text-light" %>
              </li>
              <li>
                <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light"%>
              </li>
              <li>
                <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
              </li>
              <li>
                <%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
              </li>

            <% else %>

              <li>
                <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light" %>
              </li>
              <li>
                <%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light" %>
              </li>
              <li>
                <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
              </li>
              <li>
                <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <% if flash[:notice] %>
      <div class="alert alert-primary" role="alert"><strong><%= notice %></strong></div>
    <% end %>
  
    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert"><strong><%= alert %></strong></div>
    <% end %>
    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user.html.erb
      <h2>User info</h2>
      <table class="table">
        <tr>
          <th><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></th>
        </tr>
        <tr>
          <th>name</th>
          <td><%= user.name %></td>
        </tr>
        <tr>
          <th>introduction</th>
          <td><%= user.introduction %></td>
        </tr>
      </table>
      
      <%= link_to '', edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog"%>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@user.errors.count, "error") %></h4>
    <p><% pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-5 mx-auto">
      <h2>User info</h2>

      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <p>Name</p>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <p>Image</p>
          <%= f.attachment_field :profile_image, placeholder: 'プロフィール画像'%>
        </div>
        <div class="form-group">
          <p>Introduction</p>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
          <%= f.submit 'Update User', class: "btn btn-secondary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@book.errors.count, "error") %></h4>
    <p><% pluralize(@book.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>
<div class="container">
  <div class="row mt-3">
    <div class="col-md-3">
      
      <%= render 'user', user: @user %>
      <%= render 'books/book', book: @book %>
    </div>
    
    <div class="col-md-8 offset-md-1">    
      <h2>Users</h2>
      <table class="table">
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
    
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td><%=  link_to 'Show', user_path(user) %></td>
          </tr>
        <% end%>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-3">
      <%= render 'user', user: @user %>

      <%= render 'books/book', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>

        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td>コメント数：<%= book.book_comments.count %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>